java.compatibility=17
kotlin.compatibility=2.2.0

kdoc.olderVersions=
kdoc.artifactId=kdoc
kdoc.projects=*

pom.groupId=com.apollographql.mock
pom.version=0.0.0-SNPASHOT
pom.description=Apollo Mocks
pom.vcsUrl=https://github.com/apollographql/apollo-mock
pom.developer=apollo-mock authors
pom.license=MIT

gcs.bucket=apollo-snapshots
gcs.prefix=m2