package azir.server

import com.apollographql.apollo.ast.toGQLDocument
import com.apollographql.apollo.execution.ExecutableSchema
import com.apollographql.execution.ktor.apolloModule
import com.apollographql.execution.ktor.apolloSandboxModule
import io.ktor.server.engine.embeddedServer
import io.ktor.server.netty.Netty
import java.io.File
import kotlin.system.exitProcess

private const val USAGE = """
Serves a GraphQL schema using fake entities generated by the generator module.

Usage: server --schema <schema.graphqls> --data <directory> [--port <port>]

  --schema  path to the GraphQL schema file (SDL)
  --data    directory containing the JSON files generated by the generator
  --port    port to listen on (default: 4000)
"""

fun main(args: Array<String>) {
  var schemaPath: String? = null
  var dataPath: String? = null
  var port = 4000

  var i = 0
  while (i < args.size) {
    when (args[i]) {
      "--schema" -> schemaPath = args[++i]
      "--data" -> dataPath = args[++i]
      "--port" -> port = args[++i].toInt()
      else -> {
        println(USAGE)
        exitProcess(1)
      }
    }
    i++
  }

  if (schemaPath == null || dataPath == null) {
    println(USAGE)
    exitProcess(1)
  }

  val store = EntityStore.load(File(dataPath))

  val executableSchema = ExecutableSchema.Builder()
      .schema(File(schemaPath).readText().toGQLDocument())
      .queryRoot { emptyMap<String, Any?>() }
      .resolver(FakeDataResolver(store))
      .typeResolver { obj, resolveTypeInfo ->
        (obj as? Map<*, *>)?.get("__typename") as? String
            ?: error("Cannot resolve concrete type for '$obj' (abstract type '${resolveTypeInfo.type}')")
      }
      .build()

  embeddedServer(Netty, port = port) {
    apolloModule(executableSchema)
    apolloSandboxModule()
  }.also {
    println("GraphQL endpoint: http://localhost:$port/graphql")
    println("Sandbox:          http://localhost:$port/")
  }.start(wait = true)
}
