package apollo.mock.cli

import apollo.mock.generator.generate
import apollo.mock.generator.loadGraphqlFiles
import apollo.mock.server.serve
import com.github.ajalt.clikt.core.CliktCommand
import com.github.ajalt.clikt.core.Context
import com.github.ajalt.clikt.core.main
import com.github.ajalt.clikt.core.subcommands
import com.github.ajalt.clikt.parameters.options.default
import com.github.ajalt.clikt.parameters.options.help
import com.github.ajalt.clikt.parameters.options.option
import com.github.ajalt.clikt.parameters.options.required
import com.github.ajalt.clikt.parameters.options.versionOption
import com.github.ajalt.clikt.parameters.types.int
import kotlinx.coroutines.runBlocking

private class ApolloMockCommand : CliktCommand(name = "apollo-mock") {
  init {
    versionOption(VERSION)
  }

  override fun help(context: Context): String = "Generates and serves fake data for a GraphQL schema."

  override fun run() = Unit
}

private class GenerateCommand : CliktCommand(name = "generate") {
  private val graphqlDir by option(
      "--graphql-dir",
      help = "directory containing the GraphQL files (.graphql/.graphqls): exactly one schema file, plus any number of operation files",
  ).required()
  private val outputPath by option("--output-dir", help = "directory where entity/ and operation/ JSON files are written").required()
  private val provider by option(
      "--provider",
      help = "data provider: 'ollama', 'anthropic', 'vercel' (Vercel AI Gateway), or 'random' for random data with no LLM calls",
  ).required()
  private val count by option("--count", help = "number of entities to generate per type (default: 8)").int().default(8)
  private val modelName by option(
      "--model",
      help = "model name (default: the first locally pulled model for ollama, claude-haiku-4-5 for anthropic, anthropic/claude-haiku-4.5 for vercel)",
  )
  private val baseUrl by option(
      "--base-url",
      help = "provider base url (default: http://localhost:11434 for ollama, https://ai-gateway.vercel.sh/v1 for vercel)",
  )
  private val apiKey by option(
      "--api-key",
      help = "Anthropic API key, required when --provider is 'anthropic'",
      envvar = "ANTHROPIC_API_KEY",
  )
  private val gatewayApiKey by option(
      "--gateway-api-key",
      help = "Vercel AI Gateway API key, required when --provider is 'vercel'",
      envvar = "AI_GATEWAY_API_KEY",
  )

  override fun help(context: Context): String =
      "Generates fake entities for a GraphQL schema, and mocks for @mock-annotated operations, using an LLM served by Ollama, the Anthropic API, or the Vercel AI Gateway."

  override fun run() = runBlocking {
    val graphqlFiles = loadGraphqlFiles(graphqlDir)
    generate(
        schema = graphqlFiles.schema,
        operations = graphqlFiles.operations.asSequence(),
        outputPath = outputPath,
        provider = provider,
        count = count,
        model = modelName,
        baseUrl = baseUrl,
        apiKey = if (provider == "vercel") gatewayApiKey else apiKey,
    )
  }
}

private class ServeCommand : CliktCommand(name = "serve") {
  private val schemaPath by option("--schema", help = "path to the GraphQL schema file (SDL)").required()
  private val dataPath by option("--data", help = "directory containing the JSON files generated by the generate command").required()
  private val port by option("--port", help = "port to listen on (default: 4000, use 0 to pick a free port automatically)").int().default(4000)

  override fun help(context: Context): String =
      "Serves a GraphQL schema using fake entities generated by the generate command."

  override fun run() {
    serve(schemaPath = schemaPath, dataPath = dataPath, port = port)
  }
}

fun main(args: Array<String>) = ApolloMockCommand()
    .subcommands(GenerateCommand(), ServeCommand())
    .main(args)
